"""Headless UI smoke test using streamlit.testing.v1.AppTest.

Runs the app exactly as a browser would — shared sidebar, recommendation
tabs, and (separately, because st.navigation selection is client-side) the
dashboard page — and fails on any uncaught exception in a renderer.

    python scripts/ui_smoke_test.py
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

# `streamlit run app.py` puts the script's directory on sys.path; AppTest does not.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

if hasattr(sys.stdout, "reconfigure"):          # titles contain emoji
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from streamlit.testing.v1 import AppTest  # noqa: E402

RECOMMENDATIONS = "🎬 Netflix Recommendations"
EXPECTED_TABS = 4


def _errors(at: AppTest) -> str:
    return "\n".join(
        f"{type(getattr(e, 'value', e)).__name__}: {getattr(e, 'value', e)}\n"
        f"{getattr(e, 'stack_trace', '')}"
        for e in at.exception
    )


def check_recommendations() -> str:
    """Default page: sidebar, four tabs, real results, per-user key in URL."""
    t0 = time.perf_counter()
    at = AppTest.from_file("app.py", default_timeout=300)
    at.run()
    assert not at.exception, "app raised:\n" + _errors(at)

    titles = [t.value for t in at.title]
    assert any(RECOMMENDATIONS in t for t in titles), f"missing title, got {titles}"
    print(f"[ok] default page: {titles[0]!r} in {time.perf_counter() - t0:.1f}s")

    assert len(at.sidebar.multiselect) >= 3 and len(at.sidebar.slider) >= 1, \
        "sidebar filters missing"
    print(f"[ok] sidebar: {len(at.sidebar.multiselect)} multiselects + "
          f"{len(at.sidebar.slider)} slider")

    tabs = at.get("tab")
    assert len(tabs) == EXPECTED_TABS, f"expected {EXPECTED_TABS} tabs, got {len(tabs)}"
    print(f"[ok] {len(tabs)} recommendation tabs")

    # Every tab body executes on each rerun: recommendations, seed picker,
    # watchlist panel, coverage bar and the evaluation table must all render.
    atypes = {e.type for e in at.main}
    for required in ("selectbox", "code", "progress", "arrow_data_frame", "metric"):
        assert required in atypes, f"{required} never rendered (got {sorted(atypes)})"
    print(f"[ok] rendered {len(atypes)} distinct element types")

    key = at.query_params.get("w")
    if isinstance(key, list):                 # AppTest mirrors the raw protobuf
        key = key[0] if key else None
    assert key and len(str(key)) >= 20, f"per-user key not published: {key!r}"
    print(f"[ok] per-user watchlist key in URL ({len(str(key))} chars)")

    return str(key)


def check_dashboard() -> None:
    """st.navigation picks pages client-side, so drive the dashboard directly
    after publishing the same session state app.py would publish."""
    t0 = time.perf_counter()
    page = (ROOT / "views" / "dashboard_page.py").read_text(encoding="utf-8")
    harness = ROOT / "scripts" / "_dashboard_harness.py"
    script = f'''# generated by scripts/ui_smoke_test.py -- safe to delete
import streamlit as st
st.set_page_config(page_title="Dashboard", layout="wide")
from src.data import load_data
from src.filters import apply_filters, build_sidebar
_df = load_data()
_st = build_sidebar(_df)
st.session_state["netflix_df"] = _df
st.session_state["filters"] = _st
st.session_state["filtered_df"] = apply_filters(_df, _st)
exec(compile({page!r}, "views/dashboard_page.py", "exec"))
'''
    harness.write_text(script, encoding="utf-8")
    try:
        at = AppTest.from_file(str(harness), default_timeout=300)
        at.run()
    finally:
        harness.unlink(missing_ok=True)
    assert not at.exception, "dashboard raised:\n" + _errors(at)

    atypes = {e.type for e in at.main}
    assert "plotly_chart" in atypes or "arrow_chart" in atypes, \
        f"no chart rendered (got {sorted(atypes)})"
    assert len(at.sidebar.multiselect) >= 3, "dashboard lost the shared sidebar"
    print(f"[ok] dashboard renders {len(atypes)} element types "
          f"in {time.perf_counter() - t0:.1f}s")


def main() -> int:
    t0 = time.perf_counter()
    check_recommendations()
    check_dashboard()
    print(f"\nUI SMOKE TEST PASSED in {time.perf_counter() - t0:.1f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
